name: mostly_good_metrics_flutter
description: Official Flutter SDK for MostlyGoodMetrics - Simple, privacy-focused analytics for your applications.
version: 0.2.0
homepage: https://mostlygoodmetrics.com
repository: https://github.com/Mostly-Good-Metrics/mostly-good-metrics-flutter
issue_tracker: https://github.com/Mostly-Good-Metrics/mostly-good-metrics-flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0

flutter:
